# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 21:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(db_index=True, default=None, max_length=12, null=True, unique=True)),
                ('username', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=64)),
                ('checkin_time', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('serial_format', models.CharField(blank=True, max_length=256)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Phone'), (1, 'Equipment')], default=0)),
                ('switch_type', models.CharField(max_length=256, unique=True)),
                ('skus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=[], size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Completed'), (2, 'Canceled'), (3, 'Error'), (4, 'In Progress')], default=0)),
                ('provider_id', models.CharField(max_length=128)),
                ('group_id', models.CharField(max_length=128)),
                ('completion_time', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('address_line1', models.CharField(blank=True, max_length=256)),
                ('address_line2', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('last_sync', models.DateTimeField(default=None, null=True)),
                ('sync_state', models.SmallIntegerField(choices=[(-1, 'Error'), (0, 'Clear'), (1, 'Scheduled'), (2, 'SYNC_STATE_RUNNING')], default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('provider_id', 'group_id')]),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=models.CASCADE, related_name='devices', to='deploy.DeviceType'),
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(null=True, on_delete=models.CASCADE, to='deploy.Site'),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('site', 'name')]),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='deploy.Site'),
        ),
        migrations.AddField(
            model_name='device',
            name='line_port_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='primary_user_id',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='primary_user_name',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ('manufacturer', 'model')},
        ),
        migrations.AddField(
            model_name='device',
            name='primary_user_dn',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.SmallIntegerField(choices=[(-1, 'Error'), (0, 'Clear'), (1, 'Scheduled'), (2, 'SYNC_STATE_RUNNING')], default=0),
        ),
    ]
