# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import lib.pyutil.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='device',
            name='username',
        ),
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=lib.pyutil.django.models.NullCharField(blank=True, default=None, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.SmallIntegerField(choices=[(-2, 'Provisioned'), (-1, 'Error'), (0, 'Clear'), (1, 'Scheduled'), (2, 'Running')], default=0),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Phone'), (1, 'Equipment')]),
        ),
    ]
