# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('steward', '0002_auto_20160429_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDefaultView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField()),
                ('view_name', models.CharField(max_length=256)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
