# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.SmallIntegerField(default=1)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100)),
                ('preference', models.IntegerField(default=10)),
                ('flags', models.CharField(default='U', max_length=16)),
                ('service', models.CharField(default='E2U+sip', max_length=65)),
                ('regex', models.CharField(default='!^([^@]+)@([^@]+)$!^\x01@HOST$!', max_length=128)),
                ('replacement', models.CharField(default='.', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='routing.Route'),
        ),
        migrations.AddField(
            model_name='number',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='routing.Route'),
        ),
        migrations.AlterUniqueTogether(
            name='number',
            unique_together=set([('cc', 'number')]),
        ),
    ]
