# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
