# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_number_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='destination',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
