# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_number_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(max_length=64),
        ),
    ]
