# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_auto_20160701_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='destination',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
