# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0008_auto_20160718_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmission',
            options={'ordering': ('result_timestamp',)},
        ),
    ]
