# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0010_auto_20160718_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='number',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
