# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0014_auto_20160728_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Route')], default=0),
            preserve_default=False,
        ),
    ]
