# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0015_transmission_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmission',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='transmission',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Route'), (1, 'Fraud Bypass'), (2, 'Outbound Route')]),
        ),
    ]
