# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0016_auto_20160818_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudBypass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.SmallIntegerField(default=1)),
                ('number', models.CharField(max_length=64)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('modified',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='fraudbypass',
            unique_together=set([('cc', 'number')]),
        ),
    ]
