# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0017_auto_20160818_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='type',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
