# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0018_route_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, unique=True)),
                ('comment', models.CharField(blank=True, max_length=128)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('local_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='routing.Route')),
                ('long_distance_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='routing.Route')),
            ],
            options={
                'ordering': ('modified',),
            },
        ),
    ]
