# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 15:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0021_fraudbypasshistory_outboundroutehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fraudbypass',
            options={'ordering': ('number',)},
        ),
        migrations.AlterModelOptions(
            name='outboundroute',
            options={'ordering': ('number',)},
        ),
        migrations.AlterField(
            model_name='fraudbypasshistory',
            name='number',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be 10 digits', regex='^\\d{10}$')]),
        ),
    ]
