# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 15:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0022_auto_20160819_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudbypass',
            name='number',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='fraudbypasshistory',
            name='number',
            field=models.CharField(max_length=64),
        ),
    ]
