# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-21 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0024_auto_20181220_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecallforward',
            name='called_number',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
