# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-12-21 05:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0025_auto_20181221_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecallforward',
            name='called_number',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='remotecallforward',
            name='forward_number',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be 10 digits', regex='^\\d{10}$')]),
        ),
    ]
