# Generated by Django 2.2.8 on 2020-07-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sansayvcm_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sansaycluster',
            name='route_table',
            field=models.CharField(max_length=32),
        ),
    ]
