# Generated by Django 2.2.8 on 2020-07-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sansayvcm_client', '0002_auto_20200726_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTableLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_table', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('result_status', models.CharField(max_length=32)),
                ('result_data', models.TextField()),
                ('created', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
