# Generated by Django 2.2.8 on 2020-08-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sansayvcm_client', '0003_routetablelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routetablelog',
            old_name='route_table',
            new_name='cluster_id',
        ),
        migrations.AddField(
            model_name='routetablelog',
            name='xmlcfg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='routetablelog',
            name='result_data',
            field=models.TextField(null=True),
        ),
    ]
