# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 16:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='content',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
    ]
