# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20160125_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Scheduled'), (1, 'Completed'), (2, 'Cancled'), (3, 'Error'), (4, 'Running')], default=0),
        ),
    ]
