# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 17:05
from __future__ import unicode_literals

from django.db import migrations


def update_processes(apps, schema_editor):
    Process = apps.get_model("tools", "Process")
    for process in Process.objects.all().defer('content'):
        if process.method == 'Call Park/Pickup Configurator':
            process.view_permission = 'tools.process_call_park_pickup_configurator_view'
        elif process.method == 'Device Specific Migration':
            process.view_permission = 'tools.process_device_specific_migration_view'
        elif process.method == 'Firmware Report':
            process.view_permission = 'tools.process_firmware_report_view'
        elif process.method == 'Fraud Compliance Reset':
            process.view_permission = 'tools.process_fraud_compliance_reset_view'
        elif process.method == 'Lab Rebuild':
            process.view_permission = 'tools.process_lab_rebuild_view'
        elif process.method == 'Push To Talk Configurator':
            process.view_permission = 'tools.process_ptt_configurator_view'
        elif process.method == 'Registration By Type Report':
            process.view_permission = 'tools.process_registration_by_type_view'
        elif process.method == 'Registration Report':
            process.view_permission = 'tools.process_registration_report_view'
        elif process.method == 'Tag Report':
            process.view_permission = 'tools.process_tag_report_view'
        process.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20160421_1704'),
    ]

    operations = [
        migrations.RunPython(update_processes),
    ]
