# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 21:44
from __future__ import unicode_literals

import os

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def split_process(apps, schema_editor):
    Process = apps.get_model("tools", "Process")
    ProcessContent = apps.get_model("tools", "ProcessContent")

    for process in Process.objects.all():
        for key,value in process.content.items():
            file_name = key
            tab_name = key.split('.')[0].title()
            content = ProcessContent.objects.create(process=process, tab=tab_name)
            dir_path = os.path.join(settings.MEDIA_ROOT, 'files', 'process')
            filename = '{}_{}'.format(process.id, file_name)
            pathname = os.path.join(dir_path, filename)
            if not os.path.isdir(dir_path):
                os.makedirs(dir_path)
            with open(pathname, "w") as f:
                f.write(value)
            content.raw.name = pathname
            content.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20160608_2209'),
    ]

    operations = [
        migrations.RunPython(split_process),
        migrations.RemoveField(
            model_name='process',
            name='content',
        ),
        migrations.AlterField(
            model_name='processcontent',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='tools.Process'),
        ),
    ]
