# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20160608_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processcontent',
            name='html',
            field=models.FileField(upload_to='process'),
        ),
        migrations.AlterField(
            model_name='processcontent',
            name='raw',
            field=models.FileField(upload_to='process'),
        ),
    ]
