# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-09 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20160609_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processcontent',
            options={'ordering': ['priority', 'tab']},
        ),
        migrations.AddField(
            model_name='processcontent',
            name='priority',
            field=models.PositiveSmallIntegerField(default=32767),
        ),
    ]
