# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 18:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_auto_20160627_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='parameters2',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
