# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_migrate_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='parameters',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='parameters2',
            new_name='parameters'
        ),
    ]
